### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by alvarogzp** [alvarogzp/clock-bot#3]
done:
- [x] RESULTS_TOO_MUCH
- [x] add more info in preview and in message (country, etc., emojis?)
- [x] remove country from zone?
- [x] search also on get_timezone_location
- [x] release stable version of telegram-bot and use it in requirements instead of a local copy
- [x] avoid bot to crash on network error (telegram-bot)
- [x] logging
- [x] document that you can specify country code or zone name
- [x] what if user does not have locale? should default to english!
- [x] debug=false in production
- [x] add commands to botfather
- [x] readme
- [x] improve search time (#13)
- [x] /version or /help (#10) command

postponed:
- [x] some kind of result ordering? #6
- [x] try to accept country names in english? (in your locale are accepted if search is also done on get_timezone_location) #7
- [x] storage to show popular queries? #8
- [x] country special result which display all country timezones #12

discarded:
- [x] no results result -- official bots do not return anything when no results are found
- [x] add country info via reversing pytz.country_timezones

**Comment by alvarogzp** [comment]
bot is in production, any new task should be a separate issue
